# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=26, unique=True)),
                ('longi', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('gender', models.CharField(max_length=10)),
                ('info1', models.CharField(max_length=50)),
                ('info2', models.CharField(max_length=50)),
                ('info3', models.CharField(max_length=50)),
                ('quiz1', models.CharField(max_length=15)),
                ('quiz2', models.CharField(max_length=15)),
                ('quiz3', models.CharField(max_length=15)),
                ('quiz4', models.CharField(max_length=15)),
                ('quiz5', models.CharField(max_length=15)),
                ('quizstatus', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('lookingfor', models.CharField(max_length=6)),
                ('activeprofile', models.CharField(max_length=4)),
                ('messagestatus', models.CharField(max_length=8)),
                ('intro1', models.CharField(max_length=140)),
                ('intro2', models.CharField(max_length=140)),
                ('intro3', models.CharField(max_length=140)),
                ('imageurl1', models.URLField()),
                ('imageurl2', models.URLField()),
                ('imageurl3', models.URLField()),
                ('locations', models.ManyToManyField(related_name='_user_locations_+', to='emeetlyapp.User')),
                ('matches', models.ManyToManyField(related_name='_user_matches_+', to='emeetlyapp.User')),
            ],
        ),
    ]
