# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeetlyapp', '0002_auto_20171016_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(related_name='_user_locations_+', to='emeetlyapp.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='matches',
            field=models.ManyToManyField(related_name='_user_matches_+', to='emeetlyapp.User'),
        ),
    ]
