# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeetlyapp', '0003_auto_20171020_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introstatus',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picturestatus',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
