# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeetlyapp', '0004_auto_20171023_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='messagestatus',
            field=models.CharField(default='999', max_length=8),
        ),
    ]
