# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeetlyapp', '0005_auto_20171028_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastshownpmid',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
