# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emeetlyapp', '0007_user_notmatches'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(max_length=26, unique=True)),
                ('userisinterestedinpm', models.CharField(default='notshown', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notmatches',
        ),
        migrations.AddField(
            model_name='potentialmatches',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms', to='emeetlyapp.User'),
        ),
    ]
