# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeetlyapp', '0010_auto_20171129_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instauser',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otherappdetails',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otherappname',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsappnr',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
