# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeetlyapp', '0011_auto_20171206_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferredapp',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
