# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeetlyapp', '0013_user_matchtrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastmatchid',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
