# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeetlyapp', '0014_user_lastmatchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
